version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=lecture_password
      - DB_NAME=lecture_check_db
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=1d
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lecture_password
      - MYSQL_DATABASE=lecture_check_db
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: 